# Generated by Django 3.2 on 2022-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to='infinity_photos/'),
        ),
    ]
